### ISSUE TITLE
Not able to push to devices

### ISSUE THREAD

**Issue by rajeshksv** [matiaskorhonen/alfred-bullet#2]
Hi,

After recent update of alfred workflow/push bullet app I am not able to use this workflow. Its getting stuck at "push to your devices" screen. The devices aren't getting listed and hence not able to push to them. I am able to push from pushbullet.com though.

I tried versions released on Apr 9, Apr 6 but still its not working. Please help me.

**Comment by matiaskorhonen** [comment]
Have you reset your Pushbullet password or access token recently? Could you try setting your access token again with `set-push-token` again?

There haven't been any updates to the workflow since April 9th, so nothing should have changed in the workflow…

**Comment by rajeshksv** [comment]
I tried uninstalling the workflow and installing it again. Also I tried setting up token couple of times. Still its not working. Does it show any message if entered token is valid/invalid ?

It used to work sometime before (I guess during March) and after some time, its not working for me.

**Comment by rajeshksv** [comment]
Oops I m such an idiot. I was using the extension in wrong way. After typing push, I am pressing enter and was waiting for devices to appear. Instead I should just start typing the text which will then make devices to appear! Sorry for the confusion.

Btw why are people not appearing in this list ?

**Comment by matiaskorhonen** [comment]
People don't appear in the list because that was not a feature Pushbullet supported at the time (as far as I know). I only use Pushbullet to push to my own devices, so I don't have any firm plans to add this functionality.
