### ISSUE TITLE
Can not send a whole of long text

### ISSUE THREAD

**Issue by hungmtuci** [matiaskorhonen/alfred-bullet#3]
I use Mac OS 10.9, Alfred 2 and AlfredBullet 1.0.2 with Android 4.2 and Pushbullet 4.6

It works normal if I use pushbullet from Chorme to send the whole of long text.

If I use AlfredBullet it is only able to send part of long text.

**Comment by cybrosis** [comment]
Can you specify what you mean?  

Granted I am using OSX 10.10 + PushBullet 312 (chrome) + Android 5.0.1, but I can't seem to replicate this.

I was able to push [this](https://www.google.com/search?q=push%20Miusov%2C%20as%20a%20man%20man%20of%20breeding%20and%20deilcacy%2C%20could%20not%20but%20feel%20some%20inwrd%20qualms%2C%20when%20he%20reached%20the%20Father%20Superior%27s%20with%20Ivan%3A%20he%20felt%20ashamed%20of%20havin%20lost%20his%20temper.%20He%20felt%20that%20he%20ought%20to%20have%20disdaimed%20that%20despicable%20wretch%2C%20Fyodor%20Pavlovitch%2C%20too%20much%20to%20have%20been%20upset%20by%20him%20in%20Father%20Zossima%27s%20cell%2C%20and%20so%20to%20have%20forgotten%20himself.%20%22Teh%20monks%20were%20not%20to%20blame%2C%20in%20any%20case%2C%22%20he%20reflceted%2C%20on%20the%20steps.%20%22And%20if%20they%27re%20decent%20people%20here%20%28and%20the%20Father%20Superior%2C%20I%20understand%2C%20is%20a%20nobleman%29%20why%20not%20be%20friendly%20and%20courteous%20withthem%3F%20I%20won%27t%20argue%2C%20I%27ll%20fall%20in%20with%20everything%2C%20I%27ll%20win%20them%20by%20politness%2C%20and%20show%20them%20that%20I%27ve%20nothing%20to%20do%20with%20that%20Aesop%2C%20thta%20buffoon%2C%20that%20Pierrot%2C%20and%20have%20merely%20been%20takken%20in%20over%20this%20affair%2C%20just%20as%20they%20have.%22) google search URL through alfred and the entire thing was retained when I got it on my phone.  It's over a thousand characters.

If you can you give an example I might be able to help.

**Comment by matiaskorhonen** [comment]
Closing due to a lack of details
