### ISSUE TITLE
Alfred tries to search google when I put "push something"

### ISSUE THREAD

**Issue by Jeminaa** [matiaskorhonen/alfred-bullet#7]
I've installed and set up the token.
When I type push, it seems working, but when I type something I want to push, it only shows google search option.
Am I doing something wrong?
Many thanks!!

![image](https://user-images.githubusercontent.com/22572233/34593506-4eaa889c-f206-11e7-83e3-292a8c93f161.png)

![image](https://user-images.githubusercontent.com/22572233/34593481-23164586-f206-11e7-8f15-aa3a77f13c13.png)

**Comment by matiaskorhonen** [comment]
Sorry, I'm not working on this extension any more as I don't use it myself.
